site_name: VK.PY - Modern VKAPI library for Python.
nav:
  - Get started: index.md
theme:
  name: 'material'
markdown_extensions:
  - admonition
  - codehilite

repo_name: 'prostomarkeloff/vk.py'
repo_url: 'https://github.com/prostomarkeloff/vk.py'